logo_title: Stone  Ice

style: black

favicon: /favicon.ico

menu:
  作品: /project
  关于: /about

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: false
  appId:
  appKey:

highlight:
  enable: false